services:
  mariadb:
    image: mariadb:11.4
    container_name: clinica-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Grupo_6
      MYSQL_USER: progra_c
      MYSQL_PASSWORD: progra_c
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u$$MYSQL_USER -p$$MYSQL_PASSWORD -h127.0.0.1 -e 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
      - ./db/mariadb:/docker-entrypoint-initdb.d:ro
volumes:
  db_data: